# Here are types of rows you can exclude:
# elapsed time flight state, accX, accY, accZ, gyroX,
# gyroY, gyroZ, magX, magY, magZ, baroTemp, baroPressure, events

rows-modified:
  -accY
  -accZ
  -gyroZ
mode: exclude #Can be exclude or include
graph-type: lines #Can be 'lines' or 'markers'
file-name: example.csv